#!/bin/sh

commit_regex='^(feat|fix|docs|style|refactor|test|chore)(\([a-zA-Z0-9_-]+\))?: .+'

commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -Eq "$commit_regex"; then
  echo ""
  echo "Invalid commit message"
  echo ""
  echo "Required format:"
  echo "type(scope): description"
  echo ""
  echo "Example:"
  echo "feat(auth): add login API"
  echo ""
  echo "Allowed types:"
  echo "feat | fix | docs | style | refactor | test | chore"
  exit 1
fi