name: Lint Commit Messages

on:
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Check commit messages
        run: |
          npx commitlint --from="${{ github.event.pull_request.base.sha }}" --to="${{ github.sha }}"
