name: TestCase Coverage Check

on:
  pull_request:
    branches:
      - master
      - develop
  pull_request_target:
    branches:
      - master
      - develop
    paths-ignore:
      - '**'

permissions:
  contents: read
  pull-requests: write
  issues: write



jobs:
  build-and-test-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout PR Head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven and Run Tests
        run: |
          mvn clean verify -Dmaven.test.failure.ignore=false

      - name: Upload JaCoCo Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml
          if-no-files-found: warn

  post-coverage-comment:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    needs: build-and-test-pr
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout Base Branch (for JaCoCo action context)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Download JaCoCo Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Compare JaCoCo Coverage and Post Comment
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
